channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=26.0
- pip:
  - mlflow==3.9.0
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==7.2.2
  - pyarrow==22.0.0
  - scikit-learn==1.8.0
  - scipy==1.17.0
  - xgboost==3.1.3
name: mlflow-env
